### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by KamelHtira** [RandomEngy/tauri-sqlite#1]
hello, not really an issue i just have a simple question when i build the app and send the setup to another computer that does not have SQL engine installed, will it work ? 
because i developed a desktop app with python and SQLite before, and the database won't work if the computer does not have SQL engine because the SQLite plugin didn't install it.

**Comment by aaalloc** [comment]
> hello, not really an issue i just have a simple question when i build the app and send the setup to another computer that does not have SQL engine installed, will it work ? because i developed a desktop app with python and SQLite before, and the database won't work if the computer does not have SQL engine because the SQLite plugin didn't install it.

According to https://crates.io/crates/rusqlite/

```
# `bundled` causes us to automatically compile and link in an up to date
# version of SQLite for you. This avoids many common build issues, and
# avoids depending on the version of SQLite on the users system (or your
# system), which may be old or missing. It's the right choice for most
# programs that control their own SQLite databases.
#
# That said, it's not ideal for all scenarios and in particular, generic
# libraries built around `rusqlite` should probably not enable it, which
# is why it is not a default feature -- it could become hard to disable.
rusqlite = { version = "0.29.0", features = ["bundled"] }
```

So I think the answer is yes

**Comment by KamelHtira** [comment]
I see, I am going to try it and return with results.
