### ISSUE TITLE
Consider Creating an article on Tauri docs (v2)

### ISSUE THREAD

**Issue by dvub** [RandomEngy/tauri-sqlite#2]
Hey, I'm working on a project in which I encountered the very issue you solved in this article/example. I thought it would be nice to make this more accessible by adding this to the Tauri docs?

**Comment by RandomEngy** [comment]
Glad you found it useful!

I wouldn't object to it being in there, but it would seem out of place in the base Tauri documentation. It uses a specific SQLite implementation; there's nothing else in the docs that tells you to go use a third-party library.

I think the biggest thing missing is a guide on how to work with `State`. It took me a while to figure out the Mutex<Option<Connection>> approach, and a few more examples would be really helpful, given how useful it is to access shared state in command handlers.

**Comment by dvub** [comment]
Hi,
Thanks for responding on this issue. I understand what you're saying and I completely agree. The most in-depth documentation I could find regarding `State` was [here](https://tauri.app/v1/guides/features/command/#accessing-managed-state) -- this example demonstrates a *very simple* use case for state, and doesn't discuss `Mutex`'s at all.

So maybe a section in the documentation for `State` - (and one that I will most definitely look into contributing to) would be to answer: *"How can I access `x` data type from a tauri command (that's not serializable by `serde`)?"* (in this case, it was a `rusqlite::Connection`).

Other than that, I'm sure there's an endless number of applications for app state that could go on that documentation. Anyway, that's all tangential, just sharing my thoughts. Thanks again!

**Comment by RandomEngy** [comment]
https://learn.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities

> The system assigns time slices in a round-robin fashion to all threads with the highest priority. If none of these threads are ready to run, the system assigns time slices in a round-robin fashion to all threads with the next highest priority.

So moving something from Low to Idle priority would only help processes that were marked Low.
